### ISSUE TITLE
Erro ao tentar utilizar PinPad

### ISSUE THREAD

**Issue by andre-djsystem** [paulohbsousa/flutter_clisitef#1]
Ao tentar inicializar o pinpad é retornado o seguinte erro:

`E/CliSiTefI(26765): com.loopmarket.clisitef_example: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/CliSiTefI(26765): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/CliSiTefI(26765): java.lang.IllegalArgumentException: com.loopmarket.clisitef_example: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/CliSiTefI(26765): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/CliSiTefI(26765): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
E/CliSiTefI(26765): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
E/CliSiTefI(26765): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
E/CliSiTefI(26765): 	at br.com.softwareexpress.sitef.android.PinPadDriverUSB$Driver.<init>(PinPadDriverUSB.java:154)
E/CliSiTefI(26765): 	at br.com.softwareexpress.sitef.android.PinPadDriverUSB.<init>(PinPadDriverUSB.java:390)
`

Conforme sugerido em https://stackoverflow.com/questions/71272882/in-flutter-app-targeting-s-version-31-and-above-requires-that-one-of-flag-imm adicionei a dependência androidx.work.work-runtime-ktx mas o erro ainda ocorre. 

Alguma sugestão?

**Comment by paulohbsousa** [comment]
@andre-djsystem 
Por curiosidade:
Qual modelo de PinPad esta utilizando? 
Está listado aqui https://dev.softwareexpress.com.br/docs/clisitef-interface-android/configuracao_clisitef_acesso_pinpads_externos ? 

Sobre o problema:
Parece que o problema está nesta linha da library providenciada pelo Clisitef-android.jar

 **PendingIntent var9 = PendingIntent.getBroadcast(var2.getApplicationContext(), 0, new Intent("com.android.pinpad.USB_PERMISSION"), 0);**

Parece que a flag passada pela library é "0" e o correto seria uma das flags FLAG_MUTABLE/FLAG_IMUTABLE

De acordo com a lógica do código, isso só irá acontecer se o dispositivo não possuir permissão para conectar via USB ao pinpad.

```
if (!this.mUsbManager.hasPermission(this.mUsbDevice)) {
                  PendingIntent var9 = PendingIntent.getBroadcast(var2.getApplicationContext(), 0, new Intent("com.android.pinpad.USB_PERMISSION"), 0);
                  IntentFilter var10 = new IntentFilter("com.android.pinpad.USB_PERMISSION");
                  var2.registerReceiver(this.mUsbReceiver, var10);
                  this.mUsbManager.requestPermission(this.mUsbDevice, var9);
                  this.aguardandoPermissao = true;
}

```

Para critérios de testes, conseguiria estabelecer a conexão com o pinpad e habilitar as permissões antes de rodar o exemplo?
O pinpad em questão possui bluetooth? Essa library só foi testada com pinpads bluetooth até o momento.

Obrigado

**Comment by andre-djsystem** [comment]
Obrigado pelo retorno, estou usando um Gertec PPC-930. Acabei descobrindo que utilizando o targetSdkVersion 30 funciona. Já enviei uma mensagem pro suporte da software express pedindo adequações para a versão 31 mas ainda não tive retorno.
